export default function FinanceData() {

    enum dates {
        date1 = '01/06/2025',
        date2 = '01/06/2025',
        date3 = '01/06/2025',
        date4 = '01/06/2025',
        date6 = '01/06/2025',
        date7 = '01/06/2025',
        date8 = '01/06/2025',
        date9 = '01/06/2025',
    }

    return ([
        {
            uniqueId: '1',
            category: 'Mensalidade',
            dueDate: dates.date3,
            filterDueDate: dates.date3,
            filterStartDate: dates.date4,
            packageID: 'pkg01',
            startDate: dates.date4,
            isPaid: false,
            studentName: 'João da Silva',
            isIncome: true,
            value: 100.0,
        },
        {
            uniqueId: '2',
            category: 'Material',
            dueDate: dates.date1,
            filterDueDate: dates.date1,
            filterStartDate: dates.date8,
            packageID: 'pkg01',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'João da Silva',
            isIncome: false,
            value: 120.0,
        },
        {
            uniqueId: '3',
            category: 'Mensalidade',
            dueDate: dates.date1,
            filterDueDate: dates.date1,
            filterStartDate: dates.date9,
            packageID: 'pkg02',
            startDate: dates.date9,
            isPaid: true,
            studentName: 'Maria Souza',
            isIncome: true,
            value: 500.0,
        },
        {
            uniqueId: '4',
            category: 'Uniforme',
            dueDate: dates.date2,
            filterDueDate: dates.date2,
            filterStartDate: dates.date9,
            packageID: 'pkg03',
            startDate: dates.date9,
            isPaid: false,
            studentName: 'Carlos Oliveira',
            isIncome: false,
            value: 150.0,
        },
        {
            uniqueId: '5',
            category: 'Mensalidade',
            dueDate: dates.date6,
            filterDueDate: dates.date6,
            filterStartDate: dates.date8,
            packageID: 'pkg04',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Ana Santos',
            isIncome: true,
            value: 350.0,
        },
        {
            uniqueId: '6',
            category: 'Atividade Extra',
            dueDate: dates.date7,
            filterDueDate: dates.date7,
            filterStartDate: dates.date1,
            packageID: 'pkg05',
            startDate: dates.date1,
            isPaid: true,
            studentName: 'Pedro Costa',
            isIncome: false,
            value: 80.0,
        },
        {
            uniqueId: '7',
            category: 'Mensalidade',
            dueDate: dates.date9,
            filterDueDate: dates.date9,
            filterStartDate: dates.date8,
            packageID: 'pkg06',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Luísa Fernandes',
            isIncome: false,
            value: 420.0,
        },
        {
            uniqueId: '8',
            category: 'Material',
            dueDate: dates.date2,
            filterDueDate: dates.date2,
            filterStartDate: dates.date9,
            packageID: 'pkg07',
            startDate: dates.date9,
            isPaid: false,
            studentName: 'Rafael Lima',
            isIncome: true,
            value: 95.0,
        },
        {
            uniqueId: '9',
            category: 'Mensalidade',
            dueDate: dates.date3,
            filterDueDate: dates.date3,
            filterStartDate: dates.date4,
            packageID: 'pkg08',
            startDate: dates.date4,
            isPaid: true,
            studentName: 'Fernanda Alves',
            isIncome: false,
            value: 380.0,
        },
        {
            uniqueId: '10',
            category: 'Transporte',
            dueDate: dates.date4,
            filterDueDate: dates.date4,
            filterStartDate: dates.date1,
            packageID: 'pkg09',
            startDate: dates.date1,
            isPaid: false,
            studentName: 'Gustavo Rocha',
            isIncome: true,
            value: 200.0,
        },
        {
            uniqueId: '11',
            category: 'Mensalidade',
            dueDate: dates.date2,
            filterDueDate: dates.date2,
            filterStartDate: dates.date9,
            packageID: 'pkg10',
            startDate: dates.date9,
            isPaid: false,
            studentName: 'Juliana Martins',
            isIncome: false,
            value: 450.0,
        },
        {
            uniqueId: '12',
            category: 'Atividade Extra',
            dueDate: dates.date6,
            filterDueDate: dates.date6,
            filterStartDate: dates.date8,
            packageID: 'pkg11',
            startDate: dates.date8,
            isPaid: true,
            studentName: 'Marcos Antônio',
            isIncome: true,
            value: 60.0,
        },
        {
            uniqueId: '13',
            category: 'Mensalidade',
            dueDate: dates.date1,
            filterDueDate: dates.date1,
            filterStartDate: dates.date8,
            packageID: 'pkg12',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Patrícia Nunes',
            isIncome: false,
            value: 400.0,
        },
        {
            uniqueId: '14',
            category: 'Uniforme',
            dueDate: dates.date8,
            filterDueDate: dates.date8,
            filterStartDate: dates.date9,
            packageID: 'pkg13',
            startDate: dates.date9,
            isPaid: false,
            studentName: 'Ricardo Sampaio',
            isIncome: false,
            value: 180.0,
        },
        {
            uniqueId: '15',
            category: 'Mensalidade',
            dueDate: dates.date2,
            filterDueDate: dates.date2,
            filterStartDate: dates.date8,
            packageID: 'pkg14',
            startDate: dates.date8,
            isPaid: true,
            studentName: 'Sofia Camargo',
            isIncome: true,
            value: 480.0,
        },
        {
            uniqueId: '16',
            category: 'Material',
            dueDate: dates.date7,
            filterDueDate: dates.date7,
            filterStartDate: dates.date1,
            packageID: 'pkg15',
            startDate: dates.date1,
            isPaid: false,
            studentName: 'Tiago Melo',
            isIncome: false,
            value: 45.0,
        },
        {
            uniqueId: '17',
            category: 'Mensalidade',
            dueDate: dates.date9,
            filterDueDate: dates.date9,
            filterStartDate: dates.date8,
            packageID: 'pkg16',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Vanessa Castro',
            isIncome: true,
            value: 520.0,
        },
        {
            uniqueId: '18',
            category: 'Transporte',
            dueDate: dates.date1,
            filterDueDate: dates.date1,
            filterStartDate: dates.date8,
            packageID: 'pkg17',
            startDate: dates.date8,
            isPaid: true,
            studentName: 'Bruno Peixoto',
            isIncome: true,
            value: 210.0,
        },
        {
            uniqueId: '19',
            category: 'Mensalidade',
            dueDate: dates.date6,
            filterDueDate: dates.date6,
            filterStartDate: dates.date8,
            packageID: 'pkg18',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Daniela Ramos',
            isIncome: false,
            value: 390.0,
        },
        {
            uniqueId: '20',
            category: 'Atividade Extra',
            dueDate: dates.date4,
            filterDueDate: dates.date4,
            filterStartDate: dates.date3,
            packageID: 'pkg19',
            startDate: dates.date3,
            isPaid: false,
            studentName: 'Eduardo Barros',
            isIncome: true,
            value: 90.0,
        },
        {
            uniqueId: '21',
            category: 'Mensalidade',
            dueDate: dates.date7,
            filterDueDate: dates.date7,
            filterStartDate: dates.date1,
            packageID: 'pkg20',
            startDate: dates.date1,
            isPaid: true,
            studentName: 'Flávia Dias',
            isIncome: false,
            value: 550.0,
        },
        {
            uniqueId: '22',
            category: 'Material',
            dueDate: dates.date6,
            filterDueDate: dates.date6,
            filterStartDate: dates.date8,
            packageID: 'pkg21',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Gabriel Teixeira',
            isIncome: true,
            value: 75.0,
        },
        {
            uniqueId: '23',
            category: 'Mensalidade',
            dueDate: dates.date8,
            filterDueDate: dates.date8,
            filterStartDate: dates.date9,
            packageID: 'pkg22',
            startDate: dates.date9,
            isPaid: false,
            studentName: 'Helena Correia',
            isIncome: false,
            value: 420.0,
        },
        {
            uniqueId: '24',
            category: 'Uniforme',
            dueDate: dates.date3,
            filterDueDate: dates.date3,
            filterStartDate: dates.date4,
            packageID: 'pkg23',
            startDate: dates.date4,
            isPaid: true,
            studentName: 'Igor Santos',
            isIncome: true,
            value: 120.0,
        },
        {
            uniqueId: '25',
            category: 'Mensalidade',
            dueDate: dates.date6,
            filterDueDate: dates.date6,
            filterStartDate: dates.date8,
            packageID: 'pkg24',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Laura Mendes',
            isIncome: true,
            value: 380.0,
        },
        {
            uniqueId: '26',
            category: 'Transporte',
            dueDate: dates.date4,
            filterDueDate: dates.date4,
            filterStartDate: dates.date1,
            packageID: 'pkg25',
            startDate: dates.date1,
            isPaid: false,
            studentName: 'Miguel Almeida',
            isIncome: false,
            value: 190.0,
        },
        {
            uniqueId: '27',
            category: 'Mensalidade',
            dueDate: dates.date4,
            filterDueDate: dates.date4,
            filterStartDate: dates.date3,
            packageID: 'pkg26',
            startDate: dates.date3,
            isPaid: true,
            studentName: 'Natália Rios',
            isIncome: true,
            value: 410.0,
        },
        {
            uniqueId: '28',
            category: 'Atividade Extra',
            dueDate: dates.date9,
            filterDueDate: dates.date9,
            filterStartDate: dates.date8,
            packageID: 'pkg27',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Otávio Cunha',
            isIncome: false,
            value: 65.0,
        },
        {
            uniqueId: '29',
            category: 'Mensalidade',
            dueDate: dates.date7,
            filterDueDate: dates.date7,
            filterStartDate: dates.date1,
            packageID: 'pkg28',
            startDate: dates.date1,
            isPaid: false,
            studentName: 'Paula Vasconcelos',
            isIncome: true,
            value: 470.0,
        },
        {
            uniqueId: '30',
            category: 'Material',
            dueDate: dates.date2,
            filterDueDate: dates.date2,
            filterStartDate: dates.date8,
            packageID: 'pkg29',
            startDate: dates.date8,
            isPaid: false,
            studentName: 'Roberto Andrade',
            isIncome: false,
            value: 85.0,
        }
    ])
};
